apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fanout-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: trip
          servicePort: 80
        path: /trip/(.*)
      - backend:
          serviceName: invoice
          servicePort: 80
        path: /invoice/(.*)