apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: website-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: website-deployment
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50