apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: invoice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: invoice
  minReplicas: 3
  maxReplicas: 7
  targetCPUUtilizationPercentage: 50