apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  selector:
      matchLabels:
        app: payment-service
  replicas: 1
  template:
      metadata:
        labels:
            app: payment-service
      spec:
        containers:
        - name: invoice-api
          image: vany0114/externalsystem.paymentservice
          imagePullPolicy: Always
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"         
          ports:
          - containerPort: 32777