apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: trip-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trip-deployment
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50